variables:
    SolutionBaseName: 'Prg.App.Shared.Resources'
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    ApimPolicyRoot: '$(Build.SourcesDirectory)\Resources\ApimPolicies'

resources:
  repositories:
  - repository: self
  - repository: prg-devops
    type: github
    name: uncle-sola/prg-devops
    endpoint: 'GitHub (PRG)'
    ref: refs/tags/v1.11.2

stages:
- stage: Test
  displayName: Test and Publish
  jobs:
  - job: BuildAndTestArmTemplate
    displayName: BuildAndTestArmTemplate
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/prg-arm-build.yml@prg-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)
        SolutionBaseName: '${{ variables.SolutionBaseName }}'
  - template: AzureDevOpsTemplates/Build/JobTemplates\PesterTests.yml@prg-devops
    parameters:
      CodeCoverageResultsFile: 'Pester-Coverage.xml'
      TestResultsFile: 'Test-Pester.xml'
      Tag: 'Quality'
  - template: JobTemplates\PublishFunctions.yml      

- stage: DeployToDevCalculatortApi
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_API_CALCULATOR
  variables:
  - group: prg-app-shared-resources
  - group: prg-app-shared-resources-dev
  - group: prg-shared-all
  - template: VariableTemplates\DevEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'prg (f3b14109-a3de-4f54-9f58-46d891380a7e)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(appSharedResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/prg-devops'
      PackageFile:  "$(Pipeline.Workspace)/Prg.AzureMonitorToSlack/slack_azure_function.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_APP_SHARED_RESOURCES
      SharedResourceGroup: $(appSharedResourceGroup)
      FunctionAppDomain: $(FunctionAppDomain)
      FunctionAppName: $(sharedFunctionAppName)
      SolutionBaseName: $(SolutionBaseName)
      Apis:
        -
          - azureFunctionName: '${{ variables.FunctionAppName }}'  