variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 
    ApimPolicyRoot: '$(Build.SourcesDirectory)\Resources\ApimPolicies'

resources:
  repositories:
  - repository: self
  - repository: prg-devops
    type: github
    name: uncle-sola/prg-devops
    endpoint: 'GitHub (PRG)'
    ref: refs/tags/v1.11.2

stages:
- stage: Test
  displayName: Test and Publish
  jobs:
  - job: BuildAndTestArmTemplate
    displayName: BuildAndTestArmTemplate
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/prg-arm-build.yml@prg-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)