parameters:
  AzureSubscription: ''
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  DfCDevopsPath: ''
  PackageFile:  ''
  ArmTemplateFolder: ''
  EnvironmentName: ''
  ApimProductName: ''
  SharedResourceGroup: ''
  ApimServiceName: ''
  FunctionAppDomain: ''
  ArmOutputVariableName: 'ARMOutputs'
  ApimApiName: ''
  SolutionBaseName: ''
  Apis: []
  Location: 'West Europe'
  SetEsfaResourceGroupTagsScript: 'https://raw.githubusercontent.com/olusola-adio/mon-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'
  FunctionAppName: ''

jobs:
- deployment: DeployTemplate
  displayName: "Deploy ARM Templates"
  environment: ${{ parameters.EnvironmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/deploy-arm-template.yml
          parameters: 
            AzureSubscription: '${{ parameters.AzureSubscription }}'
            DfCDevopsPath: '${{ parameters.DfCDevopsPath }}'
            SetEsfaResourceGroupTagsScript: '${{ parameters.SetEsfaResourceGroupTagsScript }}'
            EnvironmentTag: '${{ parameters.EnvironmentTag }}'
            ParentBusiness: '${{ parameters.ParentBusiness }}'
            ServiceOffering: '${{ parameters.ServiceOffering }}'
            ResourceGroup: '${{ parameters.ResourceGroup }}'
            Location: '${{ parameters.Location }}'
            ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
            ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'
            SolutionBaseName: '${{ parameters.SolutionBaseName }}'
            FunctionAppName: '${{ parameters.FunctionAppName }}'

- ${{ each apiPartition in parameters.Apis }}:
  - ${{ each api in apiPartition }}:
    - deployment: DeployFunction
      displayName: "Deploy Function"
      environment: ${{ parameters.EnvironmentName }}
      dependsOn: 
      - DeployTemplate
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../StepTemplates/deploy-azure-function.yml
              parameters:
                WebAppName: '${{ api.azureFunctionName }}'
                AzureSubscription: '${{ parameters.AzureSubscription }}'
                FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
                PackageFile: '${{ parameters.PackageFile }}'
                ResourceGroup: '${{ parameters.ResourceGroup }}'
                SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
                ApimServiceName: '${{ parameters.ApimServiceName }}'
                APIMProductName: '${{ parameters.ApimProductName }}'
                APIMApiName: '${{ parameters.ApimApiName }}'
                SolutionBaseName: '${{ parameters.SolutionBaseName }}'