parameters:
  TestsPath: ''
  ResultsPath: ''
  CodeCoverageResultsFile: ''
  TestResultsFile: ''
  Tag: ''
 

jobs:
- job: Pester
  displayName: Pester Code Quality Tests
  pool:
    vmImage: 'windows-latest'
  workspace:
      clean: all
  steps:
  - task: PowerShell@2
    displayName: 'Executing Pester Tests'
    inputs:
      filePath: '$(Build.SourcesDirectory)\tests\Pester\Pester.ps1'
      workingDirectory: '$(Build.SourcesDirectory)'
      arguments: '-TestsPath $(Build.SourcesDirectory)\${{ parameters.TestsPath }} -ResultsPath $(System.DefaultWorkingDirectory)\${{ parameters.ResultsPath }} -Publish -TestResultsFile ${{ parameters.TestResultsFile }} -CodeCoverageResultsFile ${{ parameters.CodeCoverageResultsFile }} -Tag ${{ parameters.Tag }}'
      errorActionPreference: 'silentlyContinue'
      ignoreLASTEXITCODE: true
  - task: PublishTestResults@2
    displayName: 'Publish Pester Tests'
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/${{ parameters.TestResultsFile }}'
      mergeTestResults: true
      failTaskOnFailedTests: true